### ISSUE TITLE
create flashcard lesson system

### ISSUE THREAD

**Issue by SethCohen** [SethCohen/ASLearner#4]
- [x] create lesson system UX/UI
- [x] create flashcard UX/UI
- [x] create flashcard animation/video demo system

**Comment by maakemi** [comment]
- Schema for storing a card
- Interactions of a card (flip cards)
- - THINK: how do you want to assess the learning progress? Ex.: "learned/skip" button, or present the card and have small tasks to assess
- - THINK about the homepage, what's important?
